### ISSUE TITLE
Learn about the RASD project link

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/rasd-static#5]
Reported by @TaniaGLaity 
From the draft content I provided in Feb the About the project (the icon "learn more about the RASD Project) was to link to the Plan on a Page doc.  We also have FAQs which we could include as well on an "about" page - also a link to the ALA original article could be included here perhaps as well?

**Comment by kylie-m** [comment]
Hi @TaniaGLaity, we can get these updated soon.

1. confirming this is the latest version of the [Plan on a Page](https://csiroau.sharepoint.com/:b:/r/sites/AtlasofLivingAustralia/Shared%20Documents/General/Initiatives/2022/RASD/22742%20ALA%20Restricted%20Species%20Doc.pdf?csf=1&web=1&e=syUBoK)? 
 2. For the FAQ, could you please link to the doc with that content?

**Comment by TaniaGLaity** [comment]
Hi Kylie - we updated the POAP [here](https://csiroau.sharepoint.com/:p:/r/sites/SensitiveSpeciesDataPathwaysfromResearchtoDecisionMaking/Shared%20Documents/General/Current/Comms%20Products/22742%20ALA%20Restricted%20Species%20Doc_Updated_KMedits.pptx?d=w9377949098144b798203eb0c5faf04db&csf=1&web=1&e=N5Vf0s)

The FAQs are pages 2-5 of the above and can be made into separate docs

**Comment by kylie-m** [comment]
Hi @TaniaGLaity, I've now added the 2 x separate PDF docs as we discussed yesterday, changes are now up on the production site. 

1. Plan on a Page linked from "learn more about the RASD project" icon
2. FAQ's linked from a new line of text under "About the project" (I noticed that doc has the link to the ALA blog article you mentioned, on page 1)
